### ISSUE TITLE
Would it be a big difference if I test this software in a VM

### ISSUE THREAD

**Issue by EfraMP** [pelrun/hp-omen-linux-module#14]
According to the description of the project, this is experimental and could crash my machine.

What if I just test it on a VM? Would it be a great difference? 
I just ask cause I don't have a lot of experience on VM's

**Comment by markozajc** [comment]
I'm pretty sure virtual machines don't expose the hardware interfaces required to run this module. 
Either way, you can just live boot and remove the module if the machine fails to boot. Unless it fries it, which is probably not going to happen.

**Comment by EfraMP** [comment]
Sound very reasonable and smart to me. Thanks!

**Comment by pelrun** [comment]
It's mostly a boilerplate disclaimer as I've not done any real testing, and didn't want anyone assuming this was anything more than a quick hack. But I haven't had any reports of problems.

**Comment by EfraMP** [comment]
Yeah, I know it's just a disclaimer. Thanks!
