### ISSUE TITLE
I'm a total noob to linux, Pls help me out

### ISSUE THREAD

**Issue by xenon0007** [pelrun/hp-omen-linux-module#15]
I'm new to Linux, can anyone please tell me what to do with the steps. I badly want my keyboard lighting changed. Thanks beforehand.

**Comment by wl2776** [comment]
1. Improve your skills, learn Linux. Seriously, this is a kernel. 
2. Learn how to use git and how to download the code from the GitHub.
3. Get the code from this repository to your PC, as you've learned in 2.
4. Read the file README.md, especially the part near the words "USE AT YOUR OWN RISK". Make sure you understand it.
5. Read other parts of the file README.md, they describe how to install and use this module.

[This fork of the repository](https://github.com/Scr0nch/hp-omen-linux-module) contains reworded README.md. 

Look at it, probably, things become clearer.

**Comment by dedius** [comment]
You need first to download this library, to install the module to run `sudo make install` inside the main folder. After restarting the system if you have secure boot enabled, you need to Enrol MOK key and insert the password you created during the module installation.

To change the colors scheme, I was able just using this command:
`sudo bash -c 'echo 0xffffff > /sys/devices/platform/hp-wmi/rgb_zones/zone00'`

More examples which haven't worked in my case:
`echo 0x00FFFF > /sys/devices/platform/hp-wmi/rgb_zones/zone00`
`sudo bash -c 'echo 00FFFF > /sys/devices/platform/hp-wmi/rgb_zones/zone00'`
