### ISSUE TITLE
Mouse Control

### ISSUE THREAD

**Issue by s3xxxypigispg13** [pelrun/hp-omen-linux-module#21]
Thanks for this, works flawlessly with the Omen 15 on Pop Os after Rebooting, any chance of getting this to work with the Omen Wireless Mouse(Vector)?

**Comment by pelrun** [comment]
That's out of scope for the kernel module, which only handles internal hardware controlled via ACPI. Peripherals like the mouse are going to need a userspace utility of some sort.

**Comment by s3xxxypigispg13** [comment]
Ok then, my bad, thanks for the module itself tho, works perfectly, I'm currently using it myself

**Comment by dedius** [comment]
[s3xxxypigispg13](https://github.com/s3xxxypigispg13) I think to buy this mouse model, what issues have you encountered on Linux?

**Comment by s3xxxypigispg13** [comment]
> 

I can't control the lighting
