### ISSUE TITLE
install instructions

### ISSUE THREAD

**Issue by JavierOramas** [pelrun/hp-omen-linux-module#5]
hi, can you give a install pathway

**Comment by markozajc** [comment]
https://github.com/pelrun/hp-omen-linux-module/issues/2#issuecomment-691959312 if that helps

**Comment by hockeymikey** [comment]
https://github.com/pelrun/hp-omen-linux-module/issues/3 helps more

**Comment by JavierOramas** [comment]
im having this issue when running `make` (im using manjaro 20.1.1):

make -C /lib/modules/`uname -r`/build M=$PWD
make[1]: se entra en el directorio '/usr/lib/modules/5.8.11-1-MANJARO/build'
make[1]: *** No se especificó ningún objetivo y no se encontró ningún makefile.  Alto.
make[1]: se sale del directorio '/usr/lib/modules/5.8.11-1-MANJARO/build'
make: *** [Makefile:10: default] Error 2

**Comment by hockeymikey** [comment]
Run it in the module folder

**Comment by JavierOramas** [comment]
That's where i ran it, i found an error when creating the configure file, it couldn find configure.ca

**Comment by hockeymikey** [comment]
Oh, now I see. No just run make, don't add that other crap.

**Comment by JavierOramas** [comment]
it throw this error https://github.com/pelrun/hp-omen-linux-module/issues/5#issuecomment-760401876

**Comment by hockeymikey** [comment]
@JavierOramas I told you, don't run with that parameter, just make.

**Comment by JavierOramas** [comment]
![image](https://user-images.githubusercontent.com/53378450/104856845-acce8180-58e2-11eb-9db1-43a8d640cbb2.png)
this is what i did...

**Comment by hockeymikey** [comment]
@JavierOramas You need your kernel source. I'm using the znver2 kernel from AUR so I have them from having to compile it.

**Comment by pelrun** [comment]
The kernel source isn't required, just the headers.

**Comment by pelrun** [comment]
Handled by DKMS now.
